apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-baue
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-baue
    app.kubernetes.io/part-of: build-suite-test-application-yqwx
  name: test-annotations-baue
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-annotations-baue
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-annotations-baue
    spec:
      containers:
      - image: quay.io/susdas_quay_org/build-e2e-bqrj-tenant/build-suite-test-application-yqwx/test-annotations-baue@sha256:31192b00097980a409088bf43467b8f4a17493603154a14d14e3615c1cda2e59
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
